<a href="https://colab.research.google.com/github/AshishNalawade0188/Restaurant-Analytics-Predictive-Intelligence-System/blob/main/Karthik/project_preprocess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/zomato.csv')

#BASIC EDA

In [ ]:
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  object
 1   address                      51717 non-null  object
 2   name                         51717 non-null  object
 3   online_order                 51717 non-null  object
 4   book_table                   51717 non-null  object
 5   rate                         43942 non-null  object
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  object
 8   location                     51696 non-null  object
 9   rest_type                    51490 non-null  object
 10  dish_liked                   23639 non-null  object
 11  cuisines                     51672 non-null  object
 12  approx_cost(for two people)  51371 non-null  object
 13  reviews_list                 51717 non-null  object
 14  menu_item                    51717 non-null  object
 15  listed_in(type)              51717 non-null  object
 16  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(16)
memory usage: 6.7+ MB

In [ ]:
df.describe()

              votes
count  51717.000000
mean     283.697527
std      803.838853
min        0.000000
25%        7.000000
50%       41.000000
75%      198.000000
max    16832.000000

In [ ]:
df.isnull().sum()

url                                0
address                            0
name                               0
online_order                       0
book_table                         0
rate                            7775
votes                              0
phone                           1208
location                          21
rest_type                        227
dish_liked                     28078
cuisines                          45
approx_cost(for two people)      346
reviews_list                       0
menu_item                          0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

In [ ]:
df.drop(columns=['url','address','phone','menu_item','location','reviews_list','dish_liked'],inplace=True)

# Finding out continous and categorical columns -> to later do OHE or Label Encoding

In [ ]:
categorical = df.columns[df.nunique()<=20]
categorical # will encode using ohe/label depedning on column

Index(['online_order', 'book_table', 'listed_in(type)'], dtype='object')

In [ ]:
continous = df.columns[df.nunique()>30]
continous

Index(['name', 'rate', 'votes', 'rest_type', 'cuisines',
       'approx_cost(for two people)'],
      dtype='object')

In [ ]:
df['listed_in(city)'].unique()

array(['Banashankari', 'Bannerghatta Road', 'Basavanagudi', 'Bellandur',
       'Brigade Road', 'Brookefield', 'BTM', 'Church Street',
       'Electronic City', 'Frazer Town', 'HSR', 'Indiranagar',
       'Jayanagar', 'JP Nagar', 'Kalyan Nagar', 'Kammanahalli',
       'Koramangala 4th Block', 'Koramangala 5th Block',
       'Koramangala 6th Block', 'Koramangala 7th Block', 'Lavelle Road',
       'Malleshwaram', 'Marathahalli', 'MG Road', 'New BEL Road',
       'Old Airport Road', 'Rajajinagar', 'Residency Road',
       'Sarjapur Road', 'Whitefield'], dtype=object)

In [ ]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'rest_type',
       'cuisines', 'approx_cost(for two people)', 'listed_in(type)',
       'listed_in(city)'],
      dtype='object')

#NAME

In [ ]:
df['name'] # no nulls

0                                                    Jalsa
1                                           Spice Elephant
2                                          San Churro Cafe
3                                    Addhuri Udupi Bhojana
4                                            Grand Village
                               ...
51712    Best Brews - Four Points by Sheraton Bengaluru...
51713                             Vinod Bar And Restaurant
51714    Plunge - Sheraton Grand Bengaluru Whitefield H...
51715    Chime - Sheraton Grand Bengaluru Whitefield Ho...
51716                         The Nest - The Den Bengaluru
Name: name, Length: 51717, dtype: object

Online order

In [ ]:
# no nulls
df['online_order'].unique()

array(['Yes', 'No'], dtype=object)

book tables

In [ ]:
df['book_table'].unique()

array(['Yes', 'No'], dtype=object)

#rest-type

class sklearn.preprocessing.MultiLabelBinarizer(*, classes=None, sparse_output=False)[source]
Transform between iterable of iterables and a multilabel format.

Although a list of sets or tuples is a very intuitive format for multilabel data, it is unwieldy to process. This transformer converts between this intuitive format and the supported multilabel format: a (samples x classes) binary matrix indicating the presence of a class label.

In [ ]:
df['rest_type'].unique() # doohe based on split by comma for clumn values multiple

array(['Casual Dining', 'Cafe, Casual Dining', 'Quick Bites',
       'Casual Dining, Cafe', 'Cafe', 'Quick Bites, Cafe',
       'Cafe, Quick Bites', 'Delivery', 'Mess', 'Dessert Parlor',
       'Bakery, Dessert Parlor', 'Pub', 'Bakery', 'Takeaway, Delivery',
       'Fine Dining', 'Beverage Shop', 'Sweet Shop', 'Bar',
       'Beverage Shop, Quick Bites', 'Confectionery',
       'Quick Bites, Beverage Shop', 'Dessert Parlor, Sweet Shop',
       'Bakery, Quick Bites', 'Sweet Shop, Quick Bites', 'Kiosk',
       'Food Truck', 'Quick Bites, Dessert Parlor',
       'Beverage Shop, Dessert Parlor', 'Takeaway', 'Pub, Casual Dining',
       'Casual Dining, Bar', 'Dessert Parlor, Beverage Shop',
       'Quick Bites, Bakery', 'Dessert Parlor, Quick Bites',
       'Microbrewery, Casual Dining', 'Lounge', 'Bar, Casual Dining',
       'Food Court', 'Cafe, Bakery', nan, 'Dhaba',
       'Quick Bites, Sweet Shop', 'Microbrewery',
       'Food Court, Quick Bites', 'Pub, Bar', 'Casual Dining, Pub',
       'Lounge, Bar', 'Food Court, Dessert Parlor',
       'Casual Dining, Sweet Shop', 'Food Court, Casual Dining',
       'Casual Dining, Microbrewery', 'Sweet Shop, Dessert Parlor',
       'Bakery, Beverage Shop', 'Lounge, Casual Dining',
       'Cafe, Food Court', 'Beverage Shop, Cafe', 'Cafe, Dessert Parlor',
       'Dessert Parlor, Cafe', 'Dessert Parlor, Bakery',
       'Microbrewery, Pub', 'Bakery, Food Court', 'Club',
       'Quick Bites, Food Court', 'Bakery, Cafe', 'Bar, Cafe',
       'Pub, Cafe', 'Casual Dining, Irani Cafee', 'Fine Dining, Lounge',
       'Bar, Quick Bites', 'Bakery, Kiosk', 'Pub, Microbrewery',
       'Microbrewery, Lounge', 'Fine Dining, Microbrewery',
       'Fine Dining, Bar', 'Mess, Quick Bites', 'Dessert Parlor, Kiosk',
       'Bhojanalya', 'Casual Dining, Quick Bites', 'Pop Up', 'Cafe, Bar',
       'Casual Dining, Lounge', 'Bakery, Sweet Shop', 'Microbrewery, Bar',
       'Cafe, Lounge', 'Bar, Pub', 'Lounge, Cafe', 'Club, Casual Dining',
       'Quick Bites, Mess', 'Quick Bites, Meat Shop',
       'Quick Bites, Kiosk', 'Lounge, Microbrewery',
       'Food Court, Beverage Shop', 'Dessert Parlor, Food Court',
       'Bar, Lounge'], dtype=object)

If you use MultiLabelBinarizer straight out of the box, you will create a massive matrix of binary (0 and 1) columns. If a restaurant must belong to at least one category, or if certain combinations are highly correlated, your linear regression model's coefficients can become wildly unstable, causing severe overfitting.How to fix it for Regression:Drop One Column (Or use Regularization): If you are using standard Ordinary Least Squares (LinearRegression()), you traditionally drop one of your newly created category columns to serve as the baseline reference point.Switch to Ridge or Lasso: If you keep all the columns generated by the binarizer, do not use basic Linear Regression. Switch to Ridge Regression or Lasso Regression. These variants use L1/L2 regularization to safely handle hundreds of binary encoded columns without crashing your model accuracy.

In [ ]:
df.dropna(subset=['rest_type'],inplace=True)

In [ ]:
df['rest_type'].isna().sum()

np.int64(0)

#Rate COlumn

In [ ]:
df['rate']

0         4.1/5
1         4.1/5
2         3.8/5
3         3.7/5
4         3.8/5
          ...
51712    3.6 /5
51713       NaN
51714       NaN
51715    4.3 /5
51716    3.4 /5
Name: rate, Length: 51490, dtype: object

In [ ]:
df['rate'].unique()

array(['4.1/5', '3.8/5', '3.7/5', '3.6/5', '4.6/5', '4.0/5', '4.2/5',
       '3.9/5', '3.1/5', '3.0/5', '3.2/5', '3.3/5', '2.8/5', '4.4/5',
       '4.3/5', 'NEW', '2.9/5', '3.5/5', nan, '2.6/5', '3.8 /5', '3.4/5',
       '4.5/5', '2.5/5', '2.7/5', '4.7/5', '2.4/5', '2.2/5', '2.3/5',
       '3.4 /5', '-', '3.6 /5', '4.8/5', '3.9 /5', '4.2 /5', '4.0 /5',
       '4.1 /5', '3.7 /5', '3.1 /5', '2.9 /5', '3.3 /5', '2.8 /5',
       '3.5 /5', '2.7 /5', '2.5 /5', '3.2 /5', '2.6 /5', '4.5 /5',
       '4.3 /5', '4.4 /5', '4.9/5', '2.1/5', '2.0/5', '1.8/5', '4.6 /5',
       '4.9 /5', '3.0 /5', '4.8 /5', '2.3 /5', '4.7 /5', '2.4 /5',
       '2.1 /5', '2.2 /5', '2.0 /5', '1.8 /5'], dtype=object)

In [ ]:
df['rate'] = df['rate'].astype(str).str.split('/').str[0].str.strip()
df['rate'].unique()

array(['4.1', '3.8', '3.7', '3.6', '4.6', '4.0', '4.2', '3.9', '3.1',
       '3.0', '3.2', '3.3', '2.8', '4.4', '4.3', 'NEW', '2.9', '3.5',
       'nan', '2.6', '3.4', '4.5', '2.5', '2.7', '4.7', '2.4', '2.2',
       '2.3', '-', '4.8', '4.9', '2.1', '2.0', '1.8'], dtype=object)

In [ ]:
df['rate'] = df['rate'].replace({'NEW': np.nan,'nan': np.nan, '-': np.nan})
df['rate'].isnull().sum()

np.int64(9974)

# errors='coerce' forces pandas to convert valid strings into numbers (floats).
# Any text that cannot be turned into a number (like empty spaces or text phrases) becomes NaN (Not a Number).

In [ ]:

df['rate'] = pd.to_numeric(df['rate'],errors='coerce')
df['rate'].dtype

dtype('float64')

In [ ]:
df['rate'].mean()

np.float64(3.7020979863185275)

In [ ]:
df['rate'].median()

3.7

In [ ]:
df['rate'].mode()

0    3.9
Name: rate, dtype: float64

In [ ]:
df['rate'].unique()

array([4.1, 3.8, 3.7, 3.6, 4.6, 4. , 4.2, 3.9, 3.1, 3. , 3.2, 3.3, 2.8,
       4.4, 4.3, nan, 2.9, 3.5, 2.6, 3.4, 4.5, 2.5, 2.7, 4.7, 2.4, 2.2,
       2.3, 4.8, 4.9, 2.1, 2. , 1.8])

In [ ]:
df['rate'].value_counts(0) # too many columns with 0.0 ratings

rate
3.9    3969
3.8    3867
3.7    3819
3.6    3291
4.0    3177
4.1    2948
3.5    2768
3.4    2469
3.3    2305
4.2    2184
3.2    1855
4.3    1693
3.1    1555
4.4    1147
3.0    1003
2.9     802
4.5     656
2.8     580
2.7     304
4.6     300
2.6     252
4.7     167
2.5     101
2.4      66
4.8      66
4.9      55
2.3      51
2.2      26
2.1      24
2.0      11
1.8       5
Name: count, dtype: int64

In [ ]:
df['rate'].isna().sum()

np.int64(9974)

In [ ]:
df['rate'] = df['rate'].fillna(df['rate'].median())

In [ ]:
df['rate'].unique()

array([4.1, 3.8, 3.7, 3.6, 4.6, 4. , 4.2, 3.9, 3.1, 3. , 3.2, 3.3, 2.8,
       4.4, 4.3, 2.9, 3.5, 2.6, 3.4, 4.5, 2.5, 2.7, 4.7, 2.4, 2.2, 2.3,
       4.8, 4.9, 2.1, 2. , 1.8])

#Votes

In [ ]:
df['votes'].nunique()

2328

In [ ]:
df['votes'].unique()

array([ 775,  787,  918, ..., 4957, 2382,  843])

In [ ]:
df['votes'].isna().sum()

np.int64(0)

In [ ]:
df['votes'].count()

np.int64(51490)

In [ ]:
df['votes'].value_counts()

votes
0       9949
4       1140
6        992
7        865
9        738
        ...
2034       1
2292       1
2749       1
3730       1
1260       1
Name: count, Length: 2328, dtype: int64

approx cost

In [ ]:
df['approx_cost(for two people)'].nunique() # keep it continous to maintain precise relationship of data

70

In [ ]:
df['approx_cost(for two people)'].unique()

array(['800', '300', '600', '700', '550', '500', '450', '650', '400',
       '900', '200', '750', '150', '850', '100', '1,200', '350', '250',
       '950', '1,000', '1,500', '1,300', '199', '80', '1,100', '160',
       '1,600', '230', '130', '50', '190', '1,700', nan, '1,400', '180',
       '1,350', '2,200', '2,000', '1,800', '1,900', '330', '2,500',
       '2,100', '3,000', '2,800', '3,400', '40', '1,250', '3,500',
       '4,000', '2,400', '2,600', '120', '1,450', '469', '70', '3,200',
       '60', '560', '240', '360', '6,000', '1,050', '2,300', '4,100',
       '5,000', '3,700', '1,650', '2,700', '4,500', '140'], dtype=object)

In [ ]:
df['approx_cost(for two people)'] = df['approx_cost(for two people)'].astype(str).replace(',',"")

In [ ]:
df['approx_cost(for two people)'] = pd.to_numeric(df['approx_cost(for two people)'],errors='coerce').astype('Int64')

In [ ]:
df['approx_cost(for two people)'].dtypes
df['approx_cost(for two people)'].unique()

<IntegerArray>
[ 800,  300,  600,  700,  550,  500,  450,  650,  400,  900,  200,  750,  150,
  850,  100, <NA>,  350,  250,  950,  199,   80,  160,  230,  130,   50,  190,
  180,  330,   40,  120,  469,   70,   60,  560,  240,  360,  140]
Length: 37, dtype: Int64

In [ ]:
df['approx_cost(for two people)'].isna().sum()

np.int64(7236)

In [ ]:
df['approx_cost(for two people)'].mean()

np.float64(416.6657251321914)

In [ ]:
df['approx_cost(for two people)'].median()

np.float64(400.0)

Because the Mean (416.6) > Median (400) > Mode (300), the dataset is pulled to the right by expensive outliers. A few very high-priced restaurants are inflating the overall average cost, while the vast majority of restaurants cluster around a cheaper price point (300–400).

#Imputing nulls

In [ ]:
df['approx_cost(for two people)'] = df['approx_cost(for two people)'].fillna(df['approx_cost(for two people)'].median()) # median less affected by outliers as compared to mean

In [ ]:
df['approx_cost(for two people)'].isna().sum() # No Nulls

np.int64(0)

In [ ]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'rest_type',
       'cuisines', 'approx_cost(for two people)', 'listed_in(type)',
       'listed_in(city)'],
      dtype='object')

# Cuisines

In [ ]:
df['cuisines'].nunique()

2712

In [ ]:
df['cuisines'].isnull().sum()

np.int64(24)

In [ ]:
df['cuisines'] = df['cuisines'].replace(['NaN', 'None', 'null'], np.nan)

In [ ]:
df['cuisines'].mode()

0    North Indian
Name: cuisines, dtype: object

In [ ]:
df['cuisines'].fillna(df['cuisines'].mode()[0], inplace=True)

/tmp/ipykernel_2414/3813426408.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['cuisines'].fillna(df['cuisines'].mode()[0], inplace=True)

In [ ]:
df['cuisines'].isna().sum()

np.int64(0)

In [ ]:
df['cuisines'].count()

np.int64(51490)

listed in type

In [ ]:
df['listed_in(type)'].unique()

array(['Buffet', 'Cafes', 'Delivery', 'Desserts', 'Dine-out',
       'Drinks & nightlife', 'Pubs and bars'], dtype=object)

In [ ]:
df['listed_in(type)'].isna().sum()

np.int64(0)

listed in city

In [ ]:
df['listed_in(city)'].unique()

array(['Banashankari', 'Bannerghatta Road', 'Basavanagudi', 'Bellandur',
       'Brigade Road', 'Brookefield', 'BTM', 'Church Street',
       'Electronic City', 'Frazer Town', 'HSR', 'Indiranagar',
       'Jayanagar', 'JP Nagar', 'Kalyan Nagar', 'Kammanahalli',
       'Koramangala 4th Block', 'Koramangala 5th Block',
       'Koramangala 6th Block', 'Koramangala 7th Block', 'Lavelle Road',
       'Malleshwaram', 'Marathahalli', 'MG Road', 'New BEL Road',
       'Old Airport Road', 'Rajajinagar', 'Residency Road',
       'Sarjapur Road', 'Whitefield'], dtype=object)

In [ ]:
df['listed_in(city)'].isna().sum()

np.int64(0)

# Dropping Duplicates

In [ ]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'rest_type',
       'cuisines', 'approx_cost(for two people)', 'listed_in(type)',
       'listed_in(city)'],
      dtype='object')

In [ ]:
df

,name,online_order,book_table,rate,votes,rest_type,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,Casual Dining,"North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,Casual Dining,"Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,"Cafe, Casual Dining","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,Quick Bites,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,Casual Dining,"North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6,27,Bar,Continental,400,Pubs and bars,Whitefield
51713,Vinod Bar And Restaurant,No,No,3.7,0,Bar,Finger Food,600,Pubs and bars,Whitefield
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,3.7,0,Bar,Finger Food,400,Pubs and bars,Whitefield
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3,236,Bar,Finger Food,400,Pubs and bars,Whitefield
51716,The Nest - The Den Bengaluru,No,No,3.4,13,"Bar, Casual Dining","Finger Food, North Indian, Continental",400,Pubs and bars,Whitefield

In [ ]:
df.shape

(51490, 10)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(51366, 10)

#Encoding Categorical Columns and Scaling Continous Columns Together Using *Column Transformer

A Column Transformer is a data preprocessing tool in machine learning that allows you to apply separate transformations to different columns of your dataset simultaneously.Why Use a Column Transformer?Handles mixed data types: Processes numerical and categorical variables at the same time.Prevents data leakage: Integrates seamlessly into machine learning pipelines.Keeps code clean: Replaces manual, repetitive pandas slicing.

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [ ]:
print(categorical)
print(continous)

Index(['online_order', 'book_table', 'listed_in(type)'], dtype='object')
Index(['name', 'rate', 'votes', 'rest_type', 'cuisines',
       'approx_cost(for two people)'],
      dtype='object')

# Read : https://scikit-learn.org/stable/auto_examples/compose/plot_column_transformer_mixed_types.html

In [ ]:
# OHE

In [ ]:
df_ohe = pd.get_dummies(df,columns=categorical,dtype=int)
print(df_ohe)

                                                    name  rate  votes  \
0                                                  Jalsa   4.1    775
1                                         Spice Elephant   4.1    787
2                                        San Churro Cafe   3.8    918
3                                  Addhuri Udupi Bhojana   3.7     88
4                                          Grand Village   3.8    166
...                                                  ...   ...    ...
51712  Best Brews - Four Points by Sheraton Bengaluru...   3.6     27
51713                           Vinod Bar And Restaurant   3.7      0
51714  Plunge - Sheraton Grand Bengaluru Whitefield H...   3.7      0
51715  Chime - Sheraton Grand Bengaluru Whitefield Ho...   4.3    236
51716                       The Nest - The Den Bengaluru   3.4     13

                 rest_type                                cuisines  \
0            Casual Dining          North Indian, Mughlai, Chinese
1            Casual Dining             Chinese, North Indian, Thai
2      Cafe, Casual Dining                  Cafe, Mexican, Italian
3              Quick Bites              South Indian, North Indian
4            Casual Dining                North Indian, Rajasthani
...                    ...                                     ...
51712                  Bar                             Continental
51713                  Bar                             Finger Food
51714                  Bar                             Finger Food
51715                  Bar                             Finger Food
51716   Bar, Casual Dining  Finger Food, North Indian, Continental

       approx_cost(for two people) listed_in(city)  online_order_No  \
0                              800    Banashankari                0
1                              800    Banashankari                0
2                              800    Banashankari                0
3                              300    Banashankari                1
4                              600    Banashankari                1
...                            ...             ...              ...
51712                          400      Whitefield                1
51713                          600      Whitefield                1
51714                          400      Whitefield                1
51715                          400      Whitefield                1
51716                          400      Whitefield                1

       online_order_Yes  book_table_No  book_table_Yes  \
0                     1              0               1
1                     1              1               0
2                     1              1               0
3                     0              1               0
4                     0              1               0
...                 ...            ...             ...
51712                 0              1               0
51713                 0              1               0
51714                 0              1               0
51715                 0              0               1
51716                 0              1               0

       listed_in(type)_Buffet  listed_in(type)_Cafes  \
0                           1                      0
1                           1                      0
2                           1                      0
3                           1                      0
4                           1                      0
...                       ...                    ...
51712                       0                      0
51713                       0                      0
51714                       0                      0
51715                       0                      0
51716                       0                      0

       listed_in(type)_Delivery  listed_in(type)_Desserts  \
0                             0                         0
1                             0                         0
2                             0                         0
3                             0                         0
4                             0                         0
...                         ...                       ...
51712                         0                         0
51713                         0                         0
51714                         0                         0
51715                         0                         0
51716                         0                         0

       listed_in(type)_Dine-out  listed_in(type)_Drinks & nightlife  \
0                             0                                   0
1                             0                                   0
2                             0                                   0
3                             0                                   0
4                             0                                   0
...                         ...                                 ...
51712                         0                                   0
51713                         0                                   0
51714                         0                                   0
51715                         0                                   0
51716                         0                                   0

       listed_in(type)_Pubs and bars
0                                  0
1                                  0
2                                  0
3                                  0
4                                  0
...                              ...
51712                              1
51713                              1
51714                              1
51715                              1
51716                              1

[51366 rows x 18 columns]

COrrelation

In [ ]:
df['votes'].count()
df['votes'].isna().sum()

np.int64(0)

In [ ]:
df['rate'].count()
df['rate'].isna().sum()

np.int64(0)

In [ ]:
correlation = df['votes'].corr(df['rate'])
print(f"Correlation: {correlation}")

Correlation: 0.4277386432284317